"""Add name field to schedule items

Revision ID: b03924e39223
Revises: 0001_initial
Create Date: 2025-11-17 06:58:17.445877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'b03924e39223'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    bind = op.get_bind()
    # For SQLite, use PRAGMA table_info
    if bind.dialect.name == 'sqlite':
        result = bind.execute(text(f'PRAGMA table_info("{table_name}")'))
        columns = [row[1] for row in result]
        return column_name in columns
    else:
        # For PostgreSQL and others
        from sqlalchemy import inspect
        insp = inspect(bind)
        columns = [col['name'] for col in insp.get_columns(table_name)]
        return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add column if it doesn't exist
    if not column_exists('schedule_items', 'name'):
        op.add_column('schedule_items', sa.Column('name', sa.String(length=255), nullable=True))
    # Handle foreign key constraint - check if it needs updating
    try:
        op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    except Exception:
        pass  # Constraint might not exist or have a different name
    try:
        op.create_foreign_key(None, 'schedule_items', 'schedules', ['schedule_id'], ['id'])
    except Exception:
        pass  # Constraint might already exist
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    except Exception:
        pass
    try:
        op.create_foreign_key(None, 'schedule_items', 'schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    except Exception:
        pass
    if column_exists('schedule_items', 'name'):
        op.drop_column('schedule_items', 'name')
    # ### end Alembic commands ###


